### ISSUE TITLE
Implement the artifact module

### ISSUE THREAD

**Issue by ywk253100** [goharbor/harbor#10057]
The artifact module manages the artifacts:
- [ ] List, get, delete the artifacts
- [ ] Attach/detach tag from the artifact
- [ ] Abstract detail information for different artifact types
- [ ] Clean up the useless artifact records needed by GC
