### ISSUE TITLE
Umbrella issue: Migrating docs over to the website repo

### ISSUE THREAD

**Issue by jonasrosland** [goharbor/harbor#12065]
This issue is meant to track the migration of the docs from the main /harbor repo to the /website repo. This is meant to make it easier to write, edit, and view documentation.

- [ ] Wait for the 2.0 edits to land: https://github.com/goharbor/harbor/pull/11988
- [ ] Initial docs migration to new website repo branches
- [ ] Verification that the new location works
- [ ] Migrate master branch of /harbor/docs to /website/docs
- [ ] Update the master branch on /harbor with new location information
