### ISSUE TITLE
Improve performance of APIs in harbor v2.3

### ISSUE THREAD

**Issue by heww** [goharbor/harbor#14576]
We will do and publish a performance report for harbor v2.3. More info will be published at https://github.com/goharbor/perf

Here are the APIs that will test and improve.

- [x] GET /api/v2.0/projects
- [x] GET /api/v2.0/projects/{project_name}/repositories
- [x] GET /api/v2.0/projects/{project_name}/repositories/{repository_name}/artifacts
- [x] GET /api/v2.0/projects/{project_name}/repositories/{repository_name}/artifacts/{reference}/tags
- [x] GET /api/v2.0/projects/{project_id}/members
- [x] GET /api/v2.0/projects/{project_name}/logs
- [x] GET /api/v2.0/audit-logs
- [x] GET /api/v2.0/quotas
- [x] GET /api/v2.0/users
- [x] GET /api/v2.0/users/search
- [x] GET /v2/_catalog
