### ISSUE TITLE
E2E cases for web-ui routing

### ISSUE THREAD

**Issue by YangJiao0817** [goharbor/harbor#15967]
Now there is no test case related to web-ui routing in the test case of e2e, we hope to add the corresponding test case to ensure the stability of web-ui routing

1. External routing(Open in a new tab)

- [x] navigate to API-center
![image](https://user-images.githubusercontent.com/30999793/141239309-7fd02b9e-80e6-4807-862e-845904eb65a6.png)
- [x] Open license page
![image](https://user-images.githubusercontent.com/30999793/141239408-df12702d-756c-441d-9efa-6c9324ac1c3d.png)
- [x] Click "More info" to visit the official Harbor Github repo"
![image](https://user-images.githubusercontent.com/30999793/141238400-b3897bf5-178f-4af8-9b4a-a62fd98e9824.png)
- [x] View plugable scanner Doc.
![image](https://user-images.githubusercontent.com/30999793/141239595-046689ce-7c94-4a52-a777-490dd974ad67.png)
- [ ] View CVE details 
![image](https://user-images.githubusercontent.com/30999793/141240113-efeedc57-72ff-4f0f-8fea-cccc161bd4e2.png)

2. Internal routing
    Currently our internal routing tests are based on click events, we should add tests based on Window.open(url) operations
