### ISSUE TITLE
CI improvement

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#4928]
We need to make improvement in the CI process, infrastructure and test automation:

- [x] Decouple and re-organize the jobs to form better pipelines, to run different group of test suites in different env.
- [x] Put Upgrading test of standalone into CI.
- [x] Show html test report on server.
- [x] More static checking in CI to improve the code quality.
- [x] More automation test cases in nightly test.

**Comment by wy65701436** [comment]
Close it as done.
