### ISSUE TITLE
The chart management should have the similar UE and work flow with the image management

### ISSUE THREAD

**Issue by steven-zou** [goharbor/harbor#5790]
Currently, the chart management misses several parts and then causes inconsistent experiences with image management part. The missing parts include:
- [x] Chart searching is not included in the global search results
- [x] No chart versions total number in the chart list
- [x] Mark labels to helm charts

Meanwhile, the following UE can be improved
- [x] Chart list is not sorted
- [x] The lates version can be download as deafult one on the chart list view
- [x] The chart can be deleted by deleting all the versions under it

**Comment by steven-zou** [comment]
Epic is done, close it
