### ISSUE TITLE
Sign the helm chart

### ISSUE THREAD

**Issue by steven-zou** [goharbor/harbor#5800]
The chart can be signed and the signature of the chart can be verified. The following functions should be supported to enhance the chart signing scenario:
- [ ] Allow the user to upload the prov file for an existing chart
- [ ] Support accepting the public key of the signature
- [ ] Support verifying the signature with the provided public key
- [ ] Support reading public key from file/content and keybase.io service

**Comment by wy65701436** [comment]
Since harbor is planning to deprecate chartmuseum support and so we will not support sign a chartmuseum chart.

However, for the OCI compatible chart, it can be signed with cosign that is supported in v2.5.
