### ISSUE TITLE
Support helm chart replication

### ISSUE THREAD

**Issue by steven-zou** [goharbor/harbor#5913]
As harbor has been upgraded to the cloud-native registry, helm charts should also be replicated.
Tasks should be done:

- [ ] Support helm repo checking in the registry list
- [ ] Add replicated resource kind/type in the replication policy
- [ ] Implement chart replication job
- [ ] Implement related UI for chart replication feature
